[build]
  command = "pnpm build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"



# Configure environment variable overrides for production if needed
[build.environment]
  NODE_VERSION = "20"
